// Generated by gencpp from file message/Teleop.msg
// DO NOT EDIT!


#ifndef MESSAGE_MESSAGE_TELEOP_H
#define MESSAGE_MESSAGE_TELEOP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace message
{
template <class ContainerAllocator>
struct Teleop_
{
  typedef Teleop_<ContainerAllocator> Type;

  Teleop_()
    : fwd(0.0)
    , th(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , grp(0.0)  {
    }
  Teleop_(const ContainerAllocator& _alloc)
    : fwd(0.0)
    , th(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , grp(0.0)  {
  (void)_alloc;
    }



   typedef float _fwd_type;
  _fwd_type fwd;

   typedef float _th_type;
  _th_type th;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _grp_type;
  _grp_type grp;





  typedef boost::shared_ptr< ::message::Teleop_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::message::Teleop_<ContainerAllocator> const> ConstPtr;

}; // struct Teleop_

typedef ::message::Teleop_<std::allocator<void> > Teleop;

typedef boost::shared_ptr< ::message::Teleop > TeleopPtr;
typedef boost::shared_ptr< ::message::Teleop const> TeleopConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::message::Teleop_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::message::Teleop_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace message

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'message': ['/home/zs/catkin_ws/src/message/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::message::Teleop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message::Teleop_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::message::Teleop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::message::Teleop_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message::Teleop_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message::Teleop_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::message::Teleop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d436e5173a1bafd77d003e065286d1b";
  }

  static const char* value(const ::message::Teleop_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d436e5173a1bafdULL;
  static const uint64_t static_value2 = 0x77d003e065286d1bULL;
};

template<class ContainerAllocator>
struct DataType< ::message::Teleop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "message/Teleop";
  }

  static const char* value(const ::message::Teleop_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::message::Teleop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 fwd\n\
float32 th\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 grp\n\
";
  }

  static const char* value(const ::message::Teleop_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::message::Teleop_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fwd);
      stream.next(m.th);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.grp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Teleop_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::message::Teleop_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::message::Teleop_<ContainerAllocator>& v)
  {
    s << indent << "fwd: ";
    Printer<float>::stream(s, indent + "  ", v.fwd);
    s << indent << "th: ";
    Printer<float>::stream(s, indent + "  ", v.th);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "grp: ";
    Printer<float>::stream(s, indent + "  ", v.grp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGE_MESSAGE_TELEOP_H
